UPDATE DBXX.DTXXQK05
   SET EXC_HOURS = ':EXC_HOURS',
       MEMO = ':MEMO',	
       UPDT_ID = ':UPDT_ID',
       UPDT_DATE = ':UPDT_DATE'
 WHERE EXC_DATE = ':EXC_DATE' AND EMP_ID = ':EMP_ID' AND DIV_NO = ':DIV_NO'
