WITH TA AS (
  SELECT USER_ID, CR_APPLICATION_TIME, COUNT(SEQ) AS DEV_NUM
  FROM (
    SELECT DISTINCT QP03.SEQ, QP03.USER_ID,
                    VARCHAR_FORMAT (CR_APPLICATION_TIME, 'YYYY-MM-DD') AS CR_APPLICATION_TIME
    FROM DBXX.DTXXQP03 AS QP03
    LEFT JOIN DBXX.DTXXQP04 AS QP04
    ON QP03.SEQ = QP04.SEQ
    WHERE CHECK_TYPE IN ('CR_ERROR')
      AND CR_APPLICATION_TIME BETWEEN ':START_DATE' AND ':END_DATE' AND DISP_DIV_NO = ':DIV_NO'
    [ AND USER_ID = ':EMP_ID' ]
  )
  GROUP BY USER_ID, CR_APPLICATION_TIME
),TB AS (
  SELECT USER_ID, CR_APPLICATION_TIME, SUM(NUM_OF_ERROR) AS CR_ERROR,
         LISTAGG(REMARK, CHR(13)||CHR(10)) AS ERROR_REMARK
  FROM (
    SELECT QP03.SEQ, QP03.USER_ID, NUM_OF_ERROR,QP04.REMARK,
          VARCHAR_FORMAT(CR_APPLICATION_TIME,'YYYY-MM-DD') AS CR_APPLICATION_TIME
    FROM DBXX.DTXXQP03 AS QP03
    LEFT JOIN DBXX.DTXXQP04 AS QP04
    ON QP03.SEQ = QP04.SEQ
    WHERE CHECK_TYPE IN ('CR_ERROR' )
      AND CR_APPLICATION_TIME BETWEEN ':START_DATE' AND ':END_DATE' AND DISP_DIV_NO = ':DIV_NO'
    [ AND USER_ID = ':EMP_ID' ]
  )
  GROUP BY USER_ID, CR_APPLICATION_TIME
), TC AS (
  SELECT USER_ID, CR_APPLICATION_TIME, SUM(NUM_OF_ERROR) AS CR_NOTICE,
         LISTAGG(REMARK, CHR(13)||CHR(10)) AS NOTICE_REMARK
  FROM (
    SELECT QP03.SEQ, QP03.USER_ID, NUM_OF_ERROR, QP04.REMARK,
           VARCHAR_FORMAT(CR_APPLICATION_TIME,'YYYY-MM-DD') AS CR_APPLICATION_TIME
    FROM DBXX.DTXXQP03 AS QP03
    LEFT JOIN DBXX.DTXXQP04 AS QP04
    ON QP03.SEQ = QP04.SEQ
    WHERE CHECK_TYPE IN ('CR_NOTICE')
      AND CR_APPLICATION_TIME BETWEEN ':START_DATE' AND ':END_DATE' AND DISP_DIV_NO = ':DIV_NO'
    [ AND USER_ID = ':EMP_ID' ]
  )
  GROUP BY USER_ID, CR_APPLICATION_TIME
),TD AS (
  SELECT TA.USER_ID AS EMP_ID,
         COALESCE (SUM(CR_NOTICE), 0) AS CR_NOTICE,
         COALESCE (SUM(CR_ERROR), 0) AS CR_ERROR,
         SUM(TA.DEV_NUM) AS DEV_NUM,
         CAST(CAST(VALUE(SUM(CR_NOTICE),0) AS DECIMAL(4))/CAST(SUM(DEV_NUM) AS DECIMAL(4)) AS DECIMAL(4,2)) AS NOTICE_RATE,
         CAST(CAST( SUM(CR_ERROR) AS DECIMAL(4))/CAST(SUM(DEV_NUM) AS DECIMAL(4)) AS DECIMAL(4,2)) AS ERROR_RATE
  FROM TA
  LEFT JOIN TB
  ON TA.USER_ID = TB.USER_ID
     AND TA.CR_APPLICATION_TIME = TB.CR_APPLICATION_TIME
  LEFT JOIN TC
  ON TA.USER_ID = TC.USER_ID
     AND TA.CR_APPLICATION_TIME = TC.CR_APPLICATION_TIME
  WHERE TA.CR_APPLICATION_TIME BETWEEN ':START_DATE' AND ':END_DATE'
  GROUP BY TA.USER_ID
),GRP  AS (SELECT EMP_ID, EMP_NM
   FROM DBXX.DTXXQK04
   WHERE DIV_NO = ':DIV_NO' [AND GRP_ID = ':GRP_ID'] [AND EMP_ID = ':EMP_ID']
)
SELECT  COALESCE (EMPLOYEE_ID,GRP.EMP_ID) AS EMP_ID, COALESCE (NAME,GRP.EMP_NM) AS EMP_NM, TD.CR_NOTICE,TD.CR_ERROR, TD.NOTICE_RATE AS NOTICE_RAT, TD.
      ERROR_RATE,DEV_NUM
 FROM CXLHR.DTA0_EMPLOYEE_WORK
 LEFT JOIN TD
 ON EMPLOYEE_ID = TD.EMP_ID
 FULL OUTER JOIN GRP
 ON EMPLOYEE_ID = GRP.EMP_ID
 WHERE CASE WHEN 1 = ':KIND' THEN EMPLOYEE_ID ELSE GRP.EMP_ID END
                   IS NOT NULL
       AND DIV_NO = ':DIV_NO'
      [ AND EMPLOYEE_ID = ':EMP_ID' ]
 WITH UR
