SELECT B.NAME,
       QK01.EMP_ID,
       QK01.KPI_TYPE_ID,
       SUM (QK01.KPI_VALUE) AS KPI_VALUE
  FROM    DBXX.DTXXQK01 QK01
       LEFT JOIN
          CXLHR.DTA0_EMPLOYEE B
       ON QK01.EMP_ID = B.EMPLOYEE_ID
 WHERE B.DIV_NO = ':DIV_NO'
       AND QK01.INSERT_DATE BETWEEN ':START_DATE' AND ':END_DATE'
GROUP BY QK01.KPI_TYPE_ID, QK01.EMP_ID, B.NAME
  WITH UR